query pageQuery {
  ...LayoutQueryFragment
  eventConnection {
    edges {
      node {
        id
        startDate
        endDate
        title
        _sys {
          filename
        }
      }
    }
  }
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query EventQuery($relativePath: String!) {
  ...LayoutQueryFragment
  event(relativePath: $relativePath) {
    ...EventParts
    startDate
    endDate
  }
}
