on:
    push:
    pull_request:

jobs:
    install:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        
        - name: Setup pnpm
          uses: pnpm/action-setup@v3 # docs https://pnpm.io/continuous-integration#github-actions
          
